import type { Store, Coupon, Deal, Blog, Category, BankOffer } from '@/types';

export const MOCK_STORES: Store[] = [
  {
    id: '1', name: 'Amazon', slug: 'amazon',
    logo: 'https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://www.amazon.in&size=128',
    description: 'India\'s largest online marketplace with millions of products.',
    website_url: 'https://amazon.in', affiliate_url: 'https://amazon.in',
    status: 'active', coupon_count: 45, deal_count: 120, category: 'Electronics',
  },
  {
    id: '2', name: 'Flipkart', slug: 'flipkart',
    logo: 'https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://www.flipkart.com&size=128',
    description: 'Leading e-commerce platform for electronics, fashion & more.',
    website_url: 'https://flipkart.com', affiliate_url: 'https://flipkart.com',
    status: 'active', coupon_count: 38, deal_count: 95, category: 'Electronics',
  },
  {
    id: '3', name: 'Myntra', slug: 'myntra',
    logo: 'https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://www.myntra.com&size=128',
    description: 'India\'s largest online fashion store with top brands.',
    website_url: 'https://myntra.com', affiliate_url: 'https://myntra.com',
    status: 'active', coupon_count: 22, deal_count: 67, category: 'Fashion',
  },
  {
    id: '4', name: 'Zomato', slug: 'zomato',
    logo: 'https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://www.zomato.com&size=128',
    description: 'Order food from the best restaurants near you.',
    website_url: 'https://zomato.com', affiliate_url: 'https://zomato.com',
    status: 'active', coupon_count: 15, deal_count: 30, category: 'Food & Dining',
  },
  {
    id: '5', name: 'Swiggy', slug: 'swiggy',
    logo: 'https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://www.swiggy.com&size=128',
    description: 'Fast food delivery from top restaurants.',
    website_url: 'https://swiggy.com', affiliate_url: 'https://swiggy.com',
    status: 'active', coupon_count: 18, deal_count: 25, category: 'Food & Dining',
  },
  {
    id: '6', name: 'MakeMyTrip', slug: 'makemytrip',
    logo: 'https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://www.makemytrip.com&size=128',
    description: 'Book flights, hotels & holiday packages at best prices.',
    website_url: 'https://makemytrip.com', affiliate_url: 'https://makemytrip.com',
    status: 'active', coupon_count: 12, deal_count: 40, category: 'Travel',
  },
  {
    id: '7', name: 'Nykaa', slug: 'nykaa',
    logo: 'https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://www.nykaa.com&size=128',
    description: 'Shop beauty, skincare & wellness products online.',
    website_url: 'https://nykaa.com', affiliate_url: 'https://nykaa.com',
    status: 'active', coupon_count: 20, deal_count: 55, category: 'Beauty',
  },
  {
    id: '8', name: 'Ajio', slug: 'ajio',
    logo: 'https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://www.ajio.com&size=128',
    description: 'Curated fashion from top brands and designers.',
    website_url: 'https://ajio.com', affiliate_url: 'https://ajio.com',
    status: 'active', coupon_count: 16, deal_count: 48, category: 'Fashion',
  },
  {
    id: '9', name: 'Meesho', slug: 'meesho',
    logo: 'https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://www.meesho.com&size=128',
    description: 'Shop at lowest prices across all categories.',
    website_url: 'https://meesho.com', affiliate_url: 'https://meesho.com',
    status: 'active', coupon_count: 10, deal_count: 35, category: 'Fashion',
  },
  {
    id: '10', name: 'BigBasket', slug: 'bigbasket',
    logo: 'https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://www.bigbasket.com&size=128',
    description: 'Order fresh groceries delivered to your doorstep.',
    website_url: 'https://bigbasket.com', affiliate_url: 'https://bigbasket.com',
    status: 'active', coupon_count: 14, deal_count: 28, category: 'Grocery',
  },
  {
    id: '11', name: 'Boat', slug: 'boat',
    logo: 'https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://www.boat-lifestyle.com&size=128',
    description: 'Premium audio products at affordable prices.',
    website_url: 'https://boat-lifestyle.com', affiliate_url: 'https://boat-lifestyle.com',
    status: 'active', coupon_count: 8, deal_count: 20, category: 'Electronics',
  },
  {
    id: '12', name: 'Puma', slug: 'puma',
    logo: 'https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://in.puma.com&size=128',
    description: 'Sports shoes, apparel and accessories.',
    website_url: 'https://puma.com', affiliate_url: 'https://puma.com',
    status: 'active', coupon_count: 9, deal_count: 22, category: 'Sports',
  },
];

export const MOCK_COUPONS: Coupon[] = [
  {
    id: 'c1', store_id: '1',
    store: MOCK_STORES[0],
    title: '20% Off on Electronics',
    description: 'Get flat 20% off on all electronics. Valid on select products only.',
    coupon_code: 'ELEC20',
    expiry_date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    click_count: 1245, success_count: 980, failure_count: 65,
    status: 'active', category: 'Electronics',
    is_exclusive: true, is_verified: true, discount_value: '20%', min_purchase: 999,
  },
  {
    id: 'c2', store_id: '2',
    store: MOCK_STORES[1],
    title: 'Extra ₹500 Off on Orders Above ₹2000',
    description: 'Use this code to get extra ₹500 off on your Flipkart order.',
    coupon_code: 'FLIP500',
    expiry_date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    click_count: 2100, success_count: 1800, failure_count: 120,
    status: 'active', category: 'Electronics',
    is_verified: true, discount_value: '₹500', min_purchase: 2000,
  },
  {
    id: 'c3', store_id: '3',
    store: MOCK_STORES[2],
    title: 'Flat 30% Off on Fashion',
    description: 'Enjoy 30% off on all fashion items at Myntra.',
    coupon_code: 'MYN30',
    expiry_date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    click_count: 890, success_count: 720, failure_count: 45,
    status: 'active', category: 'Fashion',
    is_exclusive: true, is_verified: true, discount_value: '30%',
  },
  {
    id: 'c4', store_id: '4',
    store: MOCK_STORES[3],
    title: '50% Off First Order on Zomato',
    description: 'New users get 50% off on their first order via Zomato.',
    coupon_code: 'ZFIRST50',
    expiry_date: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    click_count: 3200, success_count: 2900, failure_count: 100,
    status: 'active', category: 'Food & Dining',
    is_verified: true, discount_value: '50%', min_purchase: 149,
  },
  {
    id: 'c5', store_id: '5',
    store: MOCK_STORES[4],
    title: 'Free Delivery on 5 Orders',
    description: 'Get free delivery on your next 5 orders with Swiggy One.',
    coupon_code: 'SWIG5FREE',
    expiry_date: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    click_count: 1560, success_count: 1400, failure_count: 80,
    status: 'active', category: 'Food & Dining',
    is_verified: true, discount_value: 'Free Delivery',
  },
  {
    id: 'c6', store_id: '6',
    store: MOCK_STORES[5],
    title: '15% Off on Flight Bookings',
    description: 'Get 15% off on domestic and international flight bookings.',
    coupon_code: 'MMT15FLY',
    expiry_date: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
    click_count: 750, success_count: 600, failure_count: 50,
    status: 'active', category: 'Travel',
    is_exclusive: true, is_verified: true, discount_value: '15%',
  },
  {
    id: 'c7', store_id: '7',
    store: MOCK_STORES[6],
    title: 'Buy 2 Get 1 Free on Skincare',
    description: 'Buy any 2 skincare products and get 1 free on Nykaa.',
    coupon_code: 'NYK2GET1',
    expiry_date: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    click_count: 980, success_count: 850, failure_count: 60,
    status: 'active', category: 'Beauty',
    is_verified: true, discount_value: 'Buy 2 Get 1',
  },
  {
    id: 'c8', store_id: '8',
    store: MOCK_STORES[7],
    title: 'Flat 40% Off + Extra 10% with Card',
    description: 'Get flat 40% off plus extra 10% off using HDFC credit card.',
    coupon_code: 'AJIO40',
    expiry_date: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(),
    click_count: 1200, success_count: 1050, failure_count: 75,
    status: 'active', category: 'Fashion',
    is_verified: true, discount_value: '40%+10%',
  },
];

export const MOCK_DEALS: Deal[] = [
  {
    id: 'd1', store_id: '1',
    store: MOCK_STORES[0],
    title: 'Apple AirPods Pro (2nd Gen) - Limited Deal',
    description: 'Experience industry-leading noise cancellation with Apple AirPods Pro.',
    deal_url: 'https://amazon.in',
    old_price: 24900, new_price: 17499, discount_percent: 30,
    image: 'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=400&h=300&fit=crop',
    expiry_date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'active', category: 'Electronics',
    is_featured: true, is_trending: true,
  },
  {
    id: 'd2', store_id: '2',
    store: MOCK_STORES[1],
    title: 'Samsung Galaxy S24 Ultra - Flash Sale',
    description: 'The ultimate smartphone experience with 200MP camera and AI features.',
    deal_url: 'https://flipkart.com',
    old_price: 134999, new_price: 99999, discount_percent: 26,
    image: 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400&h=300&fit=crop',
    expiry_date: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'active', category: 'Electronics',
    is_featured: true, is_trending: true,
  },
  {
    id: 'd3', store_id: '3',
    store: MOCK_STORES[2],
    title: 'Levi\'s Men\'s Slim Fit Jeans',
    description: 'Classic Levi\'s jeans now at amazing discount. Limited stock.',
    deal_url: 'https://myntra.com',
    old_price: 3999, new_price: 1599, discount_percent: 60,
    image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=300&fit=crop',
    expiry_date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'active', category: 'Fashion',
    is_featured: false, is_trending: true,
  },
  {
    id: 'd4', store_id: '7',
    store: MOCK_STORES[6],
    title: 'Lakme Absolute Lip & Face Kit',
    description: 'Complete makeup kit with foundation, lipstick, and more.',
    deal_url: 'https://nykaa.com',
    old_price: 2500, new_price: 999, discount_percent: 60,
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=400&h=300&fit=crop',
    expiry_date: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'active', category: 'Beauty',
    is_featured: true, is_trending: false,
  },
  {
    id: 'd5', store_id: '6',
    store: MOCK_STORES[5],
    title: 'Goa Beach Holiday Package - 3N/4D',
    description: 'All-inclusive Goa holiday package with hotel, breakfast & sightseeing.',
    deal_url: 'https://makemytrip.com',
    old_price: 35000, new_price: 19999, discount_percent: 43,
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=400&h=300&fit=crop',
    expiry_date: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'active', category: 'Travel',
    is_featured: true, is_trending: false,
  },
  {
    id: 'd6', store_id: '1',
    store: MOCK_STORES[0],
    title: 'boAt Airdopes 141 True Wireless Earbuds',
    description: 'Upto 42hr total playback with Beast Mode for gaming.',
    deal_url: 'https://amazon.in',
    old_price: 2990, new_price: 799, discount_percent: 73,
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=300&fit=crop',
    expiry_date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'active', category: 'Electronics',
    is_featured: false, is_trending: true,
  },
  {
    id: 'd7', store_id: '10',
    store: MOCK_STORES[9],
    title: 'Fresh Organic Fruits Hamper',
    description: 'Premium organic fruits delivered fresh to your doorstep.',
    deal_url: 'https://bigbasket.com',
    old_price: 1200, new_price: 699, discount_percent: 42,
    image: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=400&h=300&fit=crop',
    expiry_date: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'active', category: 'Grocery',
    is_featured: false, is_trending: false,
  },
  {
    id: 'd8', store_id: '12',
    store: MOCK_STORES[11],
    title: 'Puma Men\'s Enzo 2 Running Shoes',
    description: 'Lightweight running shoes with responsive cushioning.',
    deal_url: 'https://puma.com',
    old_price: 6999, new_price: 2799, discount_percent: 60,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=300&fit=crop',
    expiry_date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'active', category: 'Sports',
    is_featured: false, is_trending: true,
  },
];

export const MOCK_BLOGS: Blog[] = [
  {
    id: 'b1',
    title: 'Top 10 Amazon Sale Tips to Maximize Your Savings in 2025',
    slug: 'amazon-sale-tips-2025',
    content: `<p>Amazon's Great Indian Festival is the most anticipated sale event of the year. Here are our expert tips to help you save maximum money...</p>`,
    excerpt: "Discover the secrets to getting the best deals during Amazon's biggest sale events with these pro tips.",
    thumbnail: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&h=450&fit=crop',
    author_id: 'a1', author_name: 'Priya Sharma',
    author_avatar: 'https://i.pravatar.cc/40?img=1',
    status: 'published',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    read_time: 5,
    tags: ['Amazon', 'Sale Tips', 'Shopping'],
    category: 'Shopping Tips',
  },
  {
    id: 'b2',
    title: 'Best Credit Cards for Online Shopping in India 2025',
    slug: 'best-credit-cards-online-shopping-2025',
    content: `<p>Using the right credit card can unlock additional discounts, cashback and rewards on every purchase...</p>`,
    excerpt: 'Compare the best credit cards that offer maximum cashback and rewards for online shopping in India.',
    thumbnail: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=450&fit=crop',
    author_id: 'a2', author_name: 'Rahul Verma',
    author_avatar: 'https://i.pravatar.cc/40?img=3',
    status: 'published',
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    read_time: 8,
    tags: ['Credit Cards', 'Cashback', 'Finance'],
    category: 'Finance',
  },
  {
    id: 'b3',
    title: 'Flipkart Big Billion Days 2025: Complete Deal Guide',
    slug: 'flipkart-big-billion-days-2025-guide',
    content: `<p>Flipkart's Big Billion Days is back with massive deals across all categories. Here's everything you need to know...</p>`,
    excerpt: 'Everything you need to know about Flipkart Big Billion Days - dates, best deals, and how to save more.',
    thumbnail: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&h=450&fit=crop',
    author_id: 'a3', author_name: 'Anjali Patel',
    author_avatar: 'https://i.pravatar.cc/40?img=5',
    status: 'published',
    created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    read_time: 6,
    tags: ['Flipkart', 'Sale', 'Deals'],
    category: 'Sale Events',
  },
];

export const MOCK_BANK_OFFERS: BankOffer[] = [
  {
    id: 'bo1',
    bank_name: 'HDFC Bank',
    bank_logo: 'https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://www.hdfcbank.com&size=128',
    card_type: 'Credit & Debit Card',
    discount_type: 'Instant Discount',
    discount_value: '10%',
    max_discount: '₹1,500',
    min_transaction: '₹5,000',
    valid_till: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    store_id: '1',
    store: MOCK_STORES[0],
    terms: ['Valid on select products', 'Max discount ₹1,500 per transaction', 'Not valid on EMI'],
  },
  {
    id: 'bo2',
    bank_name: 'SBI Card',
    bank_logo: 'https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://www.sbi.co.in&size=128',
    card_type: 'Credit Card',
    discount_type: 'Cashback',
    discount_value: '5%',
    max_discount: '₹2,000',
    min_transaction: '₹10,000',
    valid_till: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000).toISOString(),
    store_id: '2',
    store: MOCK_STORES[1],
    terms: ['Cashback credited within 90 days', 'Valid on all categories', 'Once per card per month'],
  },
  {
    id: 'bo3',
    bank_name: 'ICICI Bank',
    bank_logo: 'https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://www.icicibank.com&size=128',
    card_type: 'Credit Card',
    discount_type: 'Instant Discount',
    discount_value: '15%',
    max_discount: '₹3,000',
    min_transaction: '₹3,000',
    valid_till: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
    store_id: '3',
    store: MOCK_STORES[2],
    terms: ['Valid on fashion & lifestyle', 'Cannot be clubbed with other bank offers', 'Max 2 transactions per card'],
  },
  {
    id: 'bo4',
    bank_name: 'Axis Bank',
    bank_logo: 'https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://www.axisbank.com&size=128',
    card_type: 'Credit & Debit Card',
    discount_type: 'Instant Discount',
    discount_value: '12%',
    max_discount: '₹1,200',
    min_transaction: '₹2,000',
    valid_till: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
    store_id: '6',
    store: MOCK_STORES[5],
    terms: ['Valid on travel bookings only', 'Applicable on flights & hotels', 'Max discount ₹1,200'],
  },
];

export const MOCK_CATEGORIES: Category[] = [
  { id: '1', name: 'Fashion', slug: 'fashion', icon: '👗', color: '#FF6B9D', count: 234 },
  { id: '2', name: 'Electronics', slug: 'electronics', icon: '💻', color: '#60A5FA', count: 189 },
  { id: '3', name: 'Food & Dining', slug: 'food-dining', icon: '🍔', color: '#FB923C', count: 145 },
  { id: '4', name: 'Travel', slug: 'travel', icon: '✈️', color: '#34D399', count: 98 },
  { id: '5', name: 'Beauty', slug: 'beauty', icon: '💄', color: '#F472B6', count: 167 },
  { id: '6', name: 'Sports', slug: 'sports', icon: '⚽', color: '#A78BFA', count: 78 },
  { id: '7', name: 'Home & Living', slug: 'home-living', icon: '🏠', color: '#FBBF24', count: 112 },
  { id: '8', name: 'Books', slug: 'books', icon: '📚', color: '#6EE7B7', count: 55 },
  { id: '9', name: 'Grocery', slug: 'grocery', icon: '🛒', color: '#86EFAC', count: 89 },
  { id: '10', name: 'Health', slug: 'health', icon: '💊', color: '#93C5FD', count: 67 },
  { id: '11', name: 'Education', slug: 'education', icon: '🎓', color: '#FCD34D', count: 43 },
  {
    id: '12',
    name: 'Entertainment',
    slug: 'entertainment',
    icon: '🎬',
    color: '#FF3B6B',
    count: 76
  }
];

export const MOCK_POPULAR_OFFERS = [
  {
    id: '1',
    title: 'GRABFREE EXCLUSIVE',
    description: 'Exclusive Offer - Rs 500 OFF Bus Tickets: 12% Discount + 12% Cashback',
    coverImage: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?q=80&w=600&auto=format&fit=crop',
    storeLogo: 'https://upload.wikimedia.org/wikipedia/commons/e/ee/Redbus_logo.jpg',
    storeName: 'RedBus',
    color: '#FF6B35'
  },
  {
    id: '2',
    title: 'Early Bird Sale',
    description: 'Start Early & Save 50% OFF on Coursera Plus Annual Subscription',
    coverImage: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=600&auto=format&fit=crop',
    storeLogo: 'https://upload.wikimedia.org/wikipedia/commons/9/97/Coursera-Logo_600x600.svg',
    storeName: 'Coursera',
    color: '#FF3B6B'
  },
  {
    id: '3',
    title: "Today's Special",
    description: 'Laptops - Up To 40% OFF + Extra 5% OFF On Your Purchases',
    coverImage: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?q=80&w=600&auto=format&fit=crop',
    storeLogo: 'https://upload.wikimedia.org/wikipedia/commons/1/18/Dell_logo_2016.svg',
    storeName: 'Dell',
    color: '#FF6B35'
  },
  {
    id: '4',
    title: 'Up To 45% OFF',
    description: 'Grab Up To 25% OFF + Extra 20% OFF On Annual Hosting Plans',
    coverImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=600&auto=format&fit=crop',
    storeLogo: 'https://cdn.iconscout.com/icon/free/png-256/hostinger-282297.png',
    storeName: 'Hostinger',
    color: '#FF3B6B'
  }
];


